apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"EnvoyProxy","metadata":{"annotations":{},"name":"nginx-gateway-proxy","namespace":"default"},"spec":{"provider":{"kubernetes":{"envoyService":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-nlb-target-type":"instance","service.beta.kubernetes.io/aws-load-balancer-scheme":"internet-facing","service.beta.kubernetes.io/aws-load-balancer-subnets":"subnet-09eb74027a5e19fee","service.beta.kubernetes.io/aws-load-balancer-type":"external"}}},"type":"Kubernetes"}}}
  creationTimestamp: "2026-08-13T19:35:00Z"
  generation: 1
  name: nginx-gateway-proxy
  namespace: default
  resourceVersion: "51925"
  uid: 2e277390-1e05-4909-9ed9-4574995cc12e
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyService:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-09eb74027a5e19fee
          service.beta.kubernetes.io/aws-load-balancer-type: external
        externalTrafficPolicy: Local
        type: LoadBalancer
    type: Kubernetes
