apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    server_name _;\n\n    root /usr/share/nginx/html;\n    index index.html;\n\n    location / {\n        try_files $uri $uri/ /index.html;\n    }\n\n    location /nginx_status {\n        stub_status;\n        allow 127.0.0.1;\n        deny all;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-monitoring-config","namespace":"default"}}
  creationTimestamp: "2026-08-14T05:07:48Z"
  name: nginx-monitoring-config
  namespace: default
  resourceVersion: "159926"
  uid: 71e68390-c490-44c4-8611-6363eaaee528
