apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-08-13T15:34:08Z"
  labels:
    app: nginx-app
  name: nginx-service
  namespace: default
  resourceVersion: "161300"
  uid: 0a0e3bcd-b7ba-4cdc-b85a-4f7150f359fa
spec:
  clusterIP: 10.97.120.181
  clusterIPs:
  - 10.97.120.181
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
